c_compiler_version:    # [linux]
- '9'                  # [linux and not aarch64]
- '10.2.0'             # [linux and aarch64]
cxx_compiler_version:  # [linux]
- '9'                  # [linux and not aarch64]
- '10.2.0'             # [linux and aarch64]
